macro(define_lib_module module-name)
  set(_MODULE_SOURCES ${ARGN})

  foreach(BUILD_SUFFIX ${KINARA_BUILD_TYPES})
    set(_TARGET_NAME ${module-name}-${BUILD_SUFFIX})
    add_library(${_TARGET_NAME} OBJECT ${_MODULE_SOURCES})
    if(BUILD_SUFFIX MATCHES "-shared")
      set_property(TARGET ${_TARGET_NAME} PROPERTY POSITION_INDEPENDENT_CODE ON)
    endif()
    if(BUILD_SUFFIX MATCHES "lto")
      set_target_properties(${_TARGET_NAME} PROPERTIES COMPILE_OPTIONS "-O3;-flto")
    elseif(BUILD_SUFFIX MATCHES "opt")
      set_target_properties(${_TARGET_NAME} PROPERTIES COMPILE_OPTIONS "-O3")
    else()
      set_target_properties(${_TARGET_NAME} PROPERTIES COMPILE_OPTIONS "-ggdb3;-O0;-fno-inline")
    endif()
  endforeach(BUILD_SUFFIX)

endmacro(define_lib_module)
